name: Native Compiler
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup MSVC Compiler
        uses: ilammy/msvc-dev-cmd@v1

      - name: Compile Native Binary
        shell: cmd
        run: |
          cl.exe /O2 /GS- /Tc buildfolder/mhz.c /link /subsystem:native /entry:NtProcessStartup ntdll.lib /out:mhz.exe

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: native-mhz-tool
          path: mhz.exe
